### ISSUE TITLE
Unit reports invalid preset GPS altitude

### ISSUE THREAD

**Issue by jbemenheiser** [FaradayRF/Faraday-Software#63]
When a unit without a GPS is configured with set coordinates, the GPS Altitude that is returned is invalid unless it has 4 decimal points.

Configuration:
DEFAULT_ALTITUDE = 185
Returns:
"GPSALTITUDE": "185\u0000\u0000\u0000\u0000\u0000", 

Configuration:
DEFAULT_ALTITUDE = 185.000
Returns:
"GPSALTITUDE": "185.000\u0000",

Configuration:
DEFAULT_ALTITUDE = 185.0000
Returns:
"GPSALTITUDE": 185.0,

**Comment by jbemenheiser** [comment]
It appears that more than four decimals (maybe 8 total characters) overflows into other GPS data as well
Configuration:
DEFAULT_ALTITUDE = 185.00000
Returns:
"GPSALTITUDE": "\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",

**Comment by kb1lqd** [comment]
With data provided looks like an software input sanitation given expected memory format. Will reproduce and then patch.

Thanks!

**Comment by kb1lqd** [comment]
# Nominal Configuration

All fields manually set with ideal length data.

![image](https://cloud.githubusercontent.com/assets/339144/22857024/4d1b461c-f052-11e6-9211-2755413f9820.png)


![image](https://cloud.githubusercontent.com/assets/339144/22857014/32b75c5c-f052-11e6-9fac-10dc0fec90a0.png)


Verifying presence of bug on all GPS fields:

Configured every default GPS flash location to an invalid (small/large) length.

![image](https://cloud.githubusercontent.com/assets/339144/22857037/795dc8e4-f052-11e6-975a-9f6ba1d3ec8f.png)

![image](https://cloud.githubusercontent.com/assets/339144/22857051/9c642072-f052-11e6-9abc-fc76db57e4cb.png)

All data looks like "0x00's":

![image](https://cloud.githubusercontent.com/assets/339144/22857058/b6167e66-f052-11e6-8fd8-837d2caf6637.png)

**Comment by kb1lqd** [comment]
In `deviceconfig.py` we do check for maximum length:

![image](https://cloud.githubusercontent.com/assets/339144/22857083/01f2cb8c-f053-11e6-883c-79f20c31a6a0.png)

**Comment by kb1lqd** [comment]
When programming with less than the maximum/ideal bytes in numeric fields the data sent to the unit looks blank "0's":

![image](https://cloud.githubusercontent.com/assets/339144/22857098/7f8ec730-f053-11e6-83a7-58a9ec47ccc6.png)

Programming the correct number of bytes in numeric locations shows the intended data:

![image](https://cloud.githubusercontent.com/assets/339144/22857110/a18f1e2a-f053-11e6-864f-10526ef450ad.png)

**Comment by kb1lqd** [comment]
Changing just lattitude from `012345678` to `98765` shows trailing 0's in field as expected.

![image](https://cloud.githubusercontent.com/assets/339144/22857127/036b8020-f054-11e6-8977-f5143a0bedc1.png)

**Comment by kb1lqd** [comment]
# Paths Forward

The paths forward I see right now:
* Software checking forces exact lengths and errors if not
  * Easy but erroring gracefully will be difficult and also annoying
* Software checking forces exact length and corrects with padding if not
  * Easy and automatic so it lesses annoyance to user
* Firmware forces exact lengths and errors if not
  * More difficult and will use limited firmware space/processing

**Comment by kb1lqd** [comment]
Adding print debug statements in deviceconfig.py to show variables that pass max length test but (lat) shorter than max displayed as expected:

![image](https://cloud.githubusercontent.com/assets/339144/22858288/8dc0af98-f06d-11e6-8d5d-95cfe635fff5.png)

![image](https://cloud.githubusercontent.com/assets/339144/22858289/93c4b38a-f06d-11e6-8cc5-36f2372eaef9.png)

![image](https://cloud.githubusercontent.com/assets/339144/22858296/e93b1188-f06d-11e6-956b-c8144b1fb13d.png)

The data is then passed to a struct packing routine. I think the easy key here is either updating the struct packing routine or pre-packing the data.

If data is too long then only GPS fails to update the classes variables which remain 0 and therefore program 0's.

I either need to cause complete programming failure in this case to no program the device or truncate long data and allow a mis-program. I'm going to vote for the global programming failure as that is the correct thing to do.

**Comment by kb1lqd** [comment]
Completed initial bug effort: 14c90dfb1612e116b51e67c5abdfe5eea15970f8

I updated:
* Added length test status and check for global failure to deviceconfig.py so that data too long errors (could update to truncation later if wanted)
* Added other generic length checks for good practice
* Added custom padding packet creation function in commandmodule.py to pad data with specific bytes
* Force all Lat, Lon, Alt to floats and then convert back to string (all NMEA strings contain decimals)
* Padding function on Lat, Lon, Alt add 0x30 (ASCII 0) to each unused byte after data. This matches intended GPS NMEA DMM format in ASCII.

Added information in comments for clarity:
![image](https://cloud.githubusercontent.com/assets/339144/22858744/f732dfa2-f07a-11e6-8e16-1c84bc08b8e1.png)


Verified nominal length and format working:

![image](https://cloud.githubusercontent.com/assets/339144/22858726/5924118c-f07a-11e6-86bc-43b298e354ac.png)

Verified that any GPS lat, lon, alt, dir... that is too long will provide debug error and result in NOT programming the unit. (Could change this to truncation later...)

![image](https://cloud.githubusercontent.com/assets/339144/22858751/1643c046-f07b-11e6-904a-0c02a44b36f5.png)

(Note the "GPS string too long"

![image](https://cloud.githubusercontent.com/assets/339144/22858755/30a6618c-f07b-11e6-8558-30fbd168519c.png)

Verified that all fields too short (except DIR's) are padded with ASCII 0's (0x30):

![image](https://cloud.githubusercontent.com/assets/339144/22858760/504f4a30-f07b-11e6-9044-47d4579b3fba.png)


![image](https://cloud.githubusercontent.com/assets/339144/22858766/648e685a-f07b-11e6-966e-65f6012ac60d.png)



**Conclusion**

Bug effort is done unless additional updates are warranted.

**Comment by kb1lqd** [comment]
Generic configuration version: ad95cdeb4084d552a1ee966fe94906bbee06b381

**Comment by kb1lqd** [comment]
Pull request #68
